name: Pruebas API Reservas

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - user: actions/checkot@v3

      - name: Configurar Python
        uses: actions/setup-pyton@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pin install -r requirements.txt

      - name: Ejecutar Pruebas
        run: |
          source venv/bin/activate
          pytest